version: '3.8'

services:
  lake-time-series-forecasting:
    build: .
    container_name: lake-time-series-forecasting
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
